#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(gradind_scale):
    for x in range(len(gradind_scale)):
        nxt5 = math.ceil(gradind_scale[x] / 5) * 5 
        if gradind_scale[x] >= 38 and nxt5-gradind_scale[x]<3: gradind_scale[x] = nxt5  
    return gradind_scale

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    gradind_scale = []

    for x in range(grades_count):
        grades_item = int(input().strip())
        gradind_scale.append(grades_item)

    result = gradingStudents(gradind_scale)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
